services:
  mongodb:
    image: mongo:latest
    container_name: summer-body-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  metabase:
    image: metabase/metabase:latest
    container_name: summer-body-metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase.db
    restart: always

  app:
    build: .
    container_name: summer-body-bot
    restart: always
    environment:
      MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/summer-body-bot?authSource=admin
    depends_on:
      - mongodb
